_target_: masters.core.imagecas_module.ImageCASLightningModule

loss_function:
  _target_: torch.nn.MSELoss

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0007
  weight_decay: 0.0

scheduler: null
  # _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  # _partial_: true
  # mode: min
  # factor: 0.1
  # patience: 10

model:
  _target_: monai.networks.nets.UNet
  spatial_dims: 3
  in_channels: 1
  out_channels: 1
  channels: [16, 32, 64, 128, 256]
  strides: [2, 2, 2, 2]
  num_res_units: 2
  norm: BATCH
  dropout: 0.0
  bias: true
  adn_ordering: NDA

