# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.LearningRateFinder.html

learning_rate_finder:
  _target_: lightning.pytorch.callbacks.LearningRateFinder
  min_lr: 1e-8
  max_lr: 1.0
  num_training_steps: 100
  mode: exponential
  early_stop_threshold: 4.0
  update_attr: false